version: "3.9"
name: random-dc
services:
  backend: 
    build: 
      context: ./backend
      args: 
        PORT: "3006"
    container_name: random-backend
    ports: 
      - "3006:3006"
    environment:
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=3006
      - FRONTEND_HOST=localhost
      - FRONTEND_PORT=5176
  frontend:
    build: 
      context: ./frontend
      args: 
        PORT: "5176"
    container_name: random-frontend
    ports:
      - "5176:5176"
    environment:
      - VITE_BACKEND_HOST=0.0.0.0
      - VITE_BACKEND_PORT=3006
      - FRONTEND_HOST=localhost
      - FRONTEND_PORT=5176
    depends_on:
      - backend